import Footer from '@/components/footer';
import InformationBar from '@/components/information-bar';

import Navbar from '@/components/navbar/navbar';
import { getCurrentUser } from '@/lib/auth';
import { AuthProvider } from '@/providers/auth-provider';
import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';

const NunitoSans = Nunito_Sans({
  weight: ['400', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'MA.PER',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  return (
    <html lang="en">
      <body className={`${NunitoSans.className} antialiased`}>
        <AuthProvider user={user}>
          <InformationBar />
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
