import InformationBar from '@/components/information-bar';
import Navbar from '@/components/navbar';
import type { Metadata } from 'next';
import { Nunito_Sans } from 'next/font/google';
import './globals.css';

const NunitoSans = Nunito_Sans({
  weight: ['400', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NunitoSans.className} antialiased`}>
        <InformationBar />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
